[pyprland]
plugins = [ "scratchpads", "toggle_special"]

[scratchpads.drop]
animation = "fromBottom"
command = "kitty --class dropterm"
class = "dropterm"
size = "75% 45%"

[scratchpads.gemini]
animation = "fromTop"
command = "kitty --class gemini -e gemini"
class = "gemini"
# title =  Gemini - fish
size = "85% 60%"
margin = 30

[scratchpads.btop]
animation = ""
command = "kitty --class btop -e btop"
class = "btop"
size = "75% 75%"

[scratchpads.ranger]
animation = ""
command = "kitty --class ranger -e ranger"
class = "ranger"
size = "75% 75%"
